'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { money } from '@/lib/demo';
import type { CustomerAreaData } from '@/lib/customer-area';

export function CustomerArea() {
  const [data,setData]=useState<CustomerAreaData|null>(null); const [error,setError]=useState(''); const [channel,setChannel]=useState<'email'|'phone'>('email'); const [contact,setContact]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false);
  async function load(){ const res=await fetch('/api/customer/area'); const json=await res.json(); if(!res.ok){setError(json.error);return;} setData(json.data); }
  useEffect(()=>{ load(); },[]);
  async function otp(){ setBusy(true); const options={shouldCreateUser:false}; const result=channel==='email'?await createClient().auth.signInWithOtp({email:contact,options}):await createClient().auth.signInWithOtp({phone:contact,options}); setBusy(false); if(result.error)setError('Não foi possível enviar o código.'); else setSent(true); }
  async function verify(){ setBusy(true); const result=channel==='email'?await createClient().auth.verifyOtp({email:contact,token:code,type:'email'}):await createClient().auth.verifyOtp({phone:contact,token:code,type:'sms'}); setBusy(false); if(result.error)setError('Código inválido ou expirado.'); else load(); }
  if(!data) return <main className="auth-shell"><section className="auth-panel"><div className="auth-card"><span className="auth-eyebrow">Área do cliente</span><h2>Acompanhe seus atendimentos</h2><p>Entre com telefone ou e-mail e receba um código de seis dígitos.</p>{!sent?<><div className="segmented-control"><button className={channel==='email'?'active':''} onClick={()=>setChannel('email')}>E-mail</button><button className={channel==='phone'?'active':''} onClick={()=>setChannel('phone')}>Telefone</button></div><label>{channel==='email'?'E-mail':'Telefone'}<input value={contact} onChange={e=>setContact(e.target.value)} type={channel==='email'?'email':'tel'} autoComplete={channel==='email'?'email':'tel'} /></label><button className="button primary" disabled={busy||!contact} onClick={otp}>{busy?'Enviando…':'Enviar código'}</button></>:<><label>Código de confirmação<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" /></label><button className="button primary" disabled={busy||code.length!==6} onClick={verify}>{busy?'Validando…':'Entrar na área'}</button></>}{error&&<p role="alert" className="form-error">{error}</p>}</div></section></main>;
  return <main className="workspace-shell"><section className="workspace-content"><div className="page-heading"><span className="eyebrow">Área do cliente</span><h1>Olá, {data.first_name}</h1><p>{data.organization_name}</p></div><section className="panel"><h2>Meus equipamentos</h2>{data.devices.length?<div className="client-cards">{data.devices.map(d=><article className="client-card" key={d.id}><b>{d.brand} {d.model}</b><span>{d.kind} · código {d.code}</span></article>)}</div>:<p className="muted">Nenhum equipamento cadastrado.</p>}</section><section className="panel"><h2>Minhas ordens de serviço</h2>{data.orders.length?data.orders.map(o=><article className="panel" key={o.id}><div className="list-toolbar"><div><b>{o.number}</b><small>{o.device_label}</small></div><span className="status-pill status-neutral">{o.status}</span></div><p>{o.issue}</p><div className="financial-summary"><span>Total <b>{money(o.total_cents)}</b></span><span>Pago <b>{money(o.paid_cents)}</b></span><span>Saldo <b>{money(o.balance_cents)}</b></span></div></article>):<p className="muted">Nenhuma ordem encontrada.</p>}</section><button className="button secondary" onClick={()=>createClient().auth.signOut({scope:'global'}).then(()=>location.reload())}>Encerrar todas as sessões</button></section></main>;
}
