'use client';
import { useEffect, useState } from 'react';
import { useInventory, useInventoryCommand } from './inventory-view';
import { available } from '@/lib/inventory';
export function OrderStockPanel({orderId,status,liveMode,notify}:{orderId:string;status:string;liveMode:boolean;notify:(message:string,error?:boolean)=>void}){
 const [unit,setUnit]=useState<string>();const [unitError,setUnitError]=useState('');
 useEffect(()=>{if(!liveMode)return;let active=true;void fetch(`/api/orders/${orderId}`).then(async r=>{const result=await r.json();if(!r.ok)throw new Error(result.error);const id=result.data?.order?.unit_id??result.data?.unit_id;if(!id)throw new Error('Unidade da OS indisponível.');if(active)setUnit(id);}).catch(e=>{if(active)setUnitError(e.message);});return()=>{active=false;};},[orderId,liveMode]);
 if(!liveMode)return null;
 return <section className="drawer-section"><div className="section-label">Peças do estoque</div>{unit?<OrderStockContent key={unit} orderId={orderId} status={status} unit={unit} notify={notify}/>:<p>{unitError||'Carregando estoque da OS…'}</p>}</section>;
}
function OrderStockContent({orderId,status,unit,notify}:{orderId:string;status:string;unit:string;notify:(message:string,error?:boolean)=>void}){
 const {data,error,reload}=useInventory(true,unit);const command=useInventoryCommand();
 const [product,setProduct]=useState('');const [qty,setQty]=useState('1');const [busy,setBusy]=useState(false);
 async function act(action:string,payload:object){setBusy(true);try{await command(action,unit,{...payload,order_id:orderId});notify('Movimentação da peça registrada.');await reload();}catch(e){notify(e instanceof Error?e.message:'Falha ao movimentar.',true);}finally{setBusy(false);}}
 if(!data)return <p>{error||'Carregando…'}</p>;
 const manage=['gestor','atendimento','tecnico'].includes(data.role);const closed=['Cancelada','Anulada','Concluído'].includes(status);
 return <div className="inventory-form"><p className="inventory-hint">Reserve ao separar e confirme o uso para baixar o estoque. Inclua a cobrança da peça no orçamento da OS; esta movimentação controla somente o estoque.</p>{data.parts.filter(p=>p.order_id===orderId).map(p=><div className="inventory-part" key={p.id}><b>{data.products.find(i=>i.id===p.product_id)?.name}</b><span>{Number(p.quantity).toLocaleString('pt-BR')} · {({reserved:'Reservada',consumed:'Utilizada',released:'Reserva liberada',returned:'Devolvida'})[p.status]}</span>{manage&&p.status==='reserved'&&<div className="inventory-actions">{!closed&&<button className="button secondary compact" disabled={busy} onClick={()=>void act('consume',{part_id:p.id})}>Confirmar uso</button>}<button className="button secondary compact" disabled={busy} onClick={()=>void act('release',{part_id:p.id})}>Liberar reserva</button></div>}{manage&&p.status==='consumed'&&<button className="button secondary compact" disabled={busy} onClick={()=>{const reason=window.prompt('Confirme que a peça retornou fisicamente ao estoque. Informe o motivo:');if(reason&&reason.trim().length>=5)void act('restock',{part_id:p.id,reason});}}>Devolver peça ao estoque</button>}</div>)}{manage&&!closed&&<form onSubmit={e=>{e.preventDefault();void act('reserve',{product_id:product,quantity:Number(qty)});}} className="inventory-form"><label>Produto<select value={product} required onChange={e=>setProduct(e.target.value)}><option value="">Selecione</option>{data.products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} (disp. {available(data,p.id).toLocaleString('pt-BR')})</option>)}</select></label><label>Quantidade<input type="number" min="0.001" step="0.001" max="1000000" required value={qty} onChange={e=>setQty(e.target.value)}/></label><button className="button secondary" disabled={busy}>Reservar peça</button></form>}</div>;
}
